---
title: "'HiGHS' optimization solver with OMPR algebraic modeling system: A Small Example"
date: September 10, 2022
author: notesofdabbler
execute: 
  warning: false
format:
  html:
    code-fold: true
---

```{r}
# load libraries and source functions
library(highs)
library(ompr)
library(ompr.highs)
library(dplyr)
```

We show an example of using [OMPR](https://dirkschumacher.github.io/ompr/) alebraic modeling system for optimization problems with [HiGHS](https://highs.dev/) solver using R package [highs](https://cran.r-project.org/web/packages/highs/index.html). The `.qmd` file is in this [location](https://github.com/notesofdabbler/optwithR/blob/main/highs_example_ompr.qmd).

:::: {.columns}

::: {.column width="40%"}

#### Example Problem in highs package
$$
\begin{array}{ll}
\min & x_0 + x_1 + 3 \\
& x_1 \leq 7 \\
& 5 \leq x_0 + 2x_1 \leq 15 \\
& 6 \leq 3x_0 + 2x_1 \\
& 0 \leq x_0 \leq 4 \\
& 1 \leq x_1
\end{array}
$$
:::

::: {.column width="60%"}

#### OMPR model
```{r}
#| code-fold: false
mdl = MIPModel() %>%
      add_variable(x0, lb = 0, ub = 4, type = "continuous") %>%
      add_variable(x1, lb = 1, type = "continuous") %>%
      set_objective(x0+x1+3, sense = "min") %>%
      add_constraint(x1 <= 7) %>%
      add_constraint(x0 + 2*x1 <= 15) %>%
      add_constraint(x0 + 2*x1 >= 5) %>%
      add_constraint(3*x0 + 2*x1 >= 6)
```

:::
::::


```{r}
#| code-fold: false
# solve model
s = mdl %>% solve_model(highs_optimizer())

# get solution
s$status
s$objective_value
s$solution
```


::: {.callout-note collapse=true}
### Session Info

```{r}
sessionInfo()
```

:::